### ISSUE TITLE
Plugins > Explorer > Help lists wrong website

### ISSUE THREAD

**Issue by pryrt** [oviradoi/npp-explorer-plugin#14]
Plugins Admin directs people to this github as the homepage for this plugin, but the Plugins > Explorer > Help dialog still directs people to the extremely out-of-date sourceforge repo as the homepage.  

The Help dialog should be updated to link to this repo to avoid confusion.

![image](https://user-images.githubusercontent.com/17455758/81193296-10409b00-8f70-11ea-9869-d6ae861c95b1.png)

**Comment by oviradoi** [comment]
This plugin was originally written by Jens Lorenz, and he did not maintain it anymore.
I just took over his source code from Sourceforge, fixed some issues and uploaded it here in order to include it in Plugins Admin.
I did not spend too much time on improvements, just the minimum necessary to get this to work.
I hope I will have some time to work on it more in the future.

**Comment by oviradoi** [comment]
This has been fixed in the new release, [Version 1.8.9](https://github.com/oviradoi/npp-explorer-plugin/releases/tag/v1.8.9)
![image](https://user-images.githubusercontent.com/8641811/81475678-60d92200-9216-11ea-8b29-7d0e23c5289a.png)
