### ISSUE TITLE
The new version of the "Explorer" plugin does not see the localization created through the "NativeLang" plugin

### ISSUE THREAD

**Issue by andrecool-68** [oviradoi/npp-explorer-plugin#22]
This is an old version of the "Explorer" plugin and the localization is visible

![11](https://user-images.githubusercontent.com/3471892/94703351-68c16c00-0347-11eb-8dc1-f84d7f47d558.png)

This is a new version of the "Explorer" plugin and the localization is not visible

![22](https://user-images.githubusercontent.com/3471892/94703372-6bbc5c80-0347-11eb-8432-ac0ec58aad4a.png)

Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Users\Uzzer\Tools_Servis\TextCode\NPP++\npp.7.9\npp.7.9.portable\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll DSpellCheck.dll Explorer.dll HexEditor.dll HTMLTag_unicode.dll ImgTag.dll JSMinNPP.dll LocationNavigate.dll mimeTools.dll MultiClipboard.dll NativeLang.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll NppSnippets.dll ShtirlitzNppPlugin.dll Tidy2.dll VisualStudioLineCopy.dll WebEdit.dll WindowManager.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by oviradoi** [comment]
I have removed support for the NativeLang plugin in version 1.9.0 of the Explorer plugin.

This was done because of several reasons:
* the plugin was not developed anymore, and is not available inside the Plugins Admin
* the plugin was not available in 64-bit
* I wanted to simplify the codebase of the Explorer plugin, in order to ease development and bugfixing

I'm afraid I don't want to add this support back at this time, as it would add more complexity to the code. If you want to keep using this old plugin along with the translations, you can use an older version of the Explorer plugin too.
