### ISSUE TITLE
Dialog move out of desktop

### ISSUE THREAD

**Issue by SullyPanda76cl** [oviradoi/npp-explorer-plugin#4]
If moving dialog, undocking it, out of normal desktop, there's no way to moving it back, as drag operation only initiates by the titlebar, not the body of the dialog.

![npp_fav](https://user-images.githubusercontent.com/44233071/58522097-d3c7c500-818c-11e9-96ff-f65861e00ff3.png)

**Comment by oviradoi** [comment]
This can happen to any window, not just a Notepad++ plugin dialog.
You can fix this in any app using these steps:
* Click on the window in order to focus it
* Press <kbd>ALT</kbd>+<kbd>SPACE</kbd> to open the system menu for that window
* Press the <kbd>M</kbd> key, in order to activate the *Move* command from the system menu (or click on it using the mouse)
* Now you can move the window using the cursor keys and/or mouse. 
  * Tool windows (windows that have a smaller title bar height) can only be moved with the mouse after you activate the move command. The Explorer plugin's window is a tool window.
  * Regular windows (windows that have a normal title bar height) can be moved using the cursor keys and by using the mouse after you press a cursor key once).
* Once you have your window back where you want it, click on the mouse, or press <kbd>ENTER</kbd> in order to finish the move operation

The Explorer plugin does not save its own window position. Notepad++ does this for windows created by its plugins. This configuration is stored in this folder: `%APPDATA%\Notepad++\config.txt`.
