### ISSUE TITLE
Error installing plugin via Plugins Admin

### ISSUE THREAD

**Issue by abhi-shetty** [oviradoi/npp-explorer-plugin#7]
Notepad++ v7.7.1 (32-bit), trying to install Explorer 1.8.6. 
OS: Windows Server 2012 R2 Standard 64-bit

I get the following Error on start of Notepad++

---------------------------
C:\Program Files (x86)\Notepad++\plugins\Explorer\Explorer.dll
---------------------------
%1 is not a valid Win32 application.

Explorer.dll is not compatible with the current version of Notepad++.

**Comment by abhi-shetty** [comment]
Manual install by copying the dll also throws the same error on both 1.8.6 and 1.8.7 version of the plugin

**Comment by SullyPanda76cl** [comment]
I have 3 PC's, all with win10.
2 of them install ok
1 gives the error described above.

Haven't experimented long enough to give more info on differences between them

**Comment by SullyPanda76cl** [comment]
Try installing Notepad++ outside of any "c:\program file" directory:

![image](https://user-images.githubusercontent.com/44233071/62173194-247daa80-b303-11e9-8323-396211f42007.png)

**Comment by oviradoi** [comment]
Thanks for reporting this and sorry for the long delay.

This problem is happening because the Explorer plugin depends on the Microsoft Visual C++ Redistributable. Please download from here and install it: [https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

The Explorer plugin should work fine after this is installed.

I will remove this dependency in the next release of this plugin.

**Comment by oviradoi** [comment]
This should be fixed in the new release, [version 1.8.9](https://github.com/oviradoi/npp-explorer-plugin/releases/tag/v1.8.9)
